apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: amq-broker-operator-group
  namespace: amq-broker-system
spec:
  targetNamespaces:
  - amq-broker-system
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-broker-rhel8
  namespace: amq-broker-system
spec:
  channel: 7.12.x
  installPlanApproval: Automatic
  name: amq-broker-rhel8
  source: redhat-operators
  sourceNamespace: openshift-marketplace
