apiVersion: capabilities.3scale.net/v1beta1
kind: Backend
metadata:
  name: echo-backend
  annotations:
    argocd.argoproj.io/sync-wave: "15"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  name: "Echo API Backend"
  systemName: "echo-backend"
  privateBaseURL: "https://echo-api.3scale.net"
  tenantRef:
    name: internal-tenant
