apiVersion: capabilities.3scale.net/v1beta1
kind: Product
metadata:
  name: echo-api
  annotations:
    argocd.argoproj.io/sync-wave: "15"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  name: "Echo API Product"
  description: "A sample product representing an Echo API"
