apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - secrets.yaml
  - internal-tenant.yaml
  - external-tenant.yaml
  - echo-api-product.yaml
  - echo-backend.yaml
  - custom-policy.yaml
  - basic-app-plan.yaml
  - dev-account.yaml
  - dev-app.yaml
patches:
  - target:
      kind: APIManager
      name: apimanager
    patch: |-
      - op: replace
        path: /spec/wildcardDomain
        value: prod.apps.example.com
