apiVersion: v1
kind: Secret
metadata:
  name: admin-secret-internal
type: Opaque
stringData:
  admin_password: "internal-password"
---
apiVersion: v1
kind: Secret
metadata:
  name: tenant-secret-internal
type: Opaque
stringData:
  admin_access_token: "internal-access-token"
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-secret-external
type: Opaque
stringData:
  admin_password: "external-password"
---
apiVersion: v1
kind: Secret
metadata:
  name: tenant-secret-external
type: Opaque
stringData:
  admin_access_token: "external-access-token"
