apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: my-demo-topic
  namespace: amq-streams-system
  labels:
    strimzi.io/cluster: hub-kafka
  annotations:
    argocd.argoproj.io/sync-wave: "15"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
